apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-api-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: service.yaml
images:
  - name: APP_IMAGE
    newName: ghcr.io/example/python-api
    newTag: latest
replicas:
  - name: python-api
    count: 2
